### PR TITLE
Don't check channel number for send message

### PR DESCRIPTION
**Pull request by xiar**

### CODE REVIEW

**Comment by fub2** [comment]
What change of this is for?

**Comment by sharkconi** [comment]
@xiar @fub2 we need this PR or not?

**Comment by fub2** [comment]
retest this please

**Comment by fub2** [comment]
Smoke test is still failing. @xiar ?

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
@xiar @fub2 smoke test pass and this PR can be merged

**Pull request merged**
