### PR TITLE
Add "sel_list" subcommand to enable "SEL auto inject" function

### PR DESCRIPTION
**Pull request by sharkconi**
Signed-off-by: Ma, Mark Mark.Ma@emc.com

### CODE REVIEW

**Comment by sharkconi** [comment]
@turtle-fly @xiar @fub2 @PaynePei

**Comment by turtle-fly** [comment]
:+1:

**Comment by fub2** [comment]
@xiar

**Comment by PaynePei** [comment]
test this please

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
Paired with https://github.com/InfraSIM/idic/pull/12

**Pull request merged**
